# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0003_auto_20210817_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
